version: '3.8'

services:
  db:
    build:
      context: ./db
    restart: always
    environment:
      MYSQL_DATABASE: ccn_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend-django:
    build: 
      context: ./backend/django
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=ccn_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DJANGO_SECRET_KEY=supersecretkey-django123
      - DEBUG=True
    ports:
      - "8080:8000"
    depends_on:
      - db
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn core.wsgi:application --bind 0.0.0.0:8000"

  backend-fastapi:
    build: 
      context: ./backend/fastapi
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=ccn_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DJANGO_SECRET_KEY=supersecretkey-django123 # Must match Django's
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:80"

volumes:
  mysql_data:
